version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AMQP_USER=${AMQP_USER}
      - AMQP_PASSWORD=${AMQP_PASSWORD}
      - AMQP_ADDRESS=${AMQP_ADDRESS}
      - AMQP_VHOST=${AMQP_VHOST}
      - AMQP_PORT=${AMQP_PORT}
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
